Fix exception raised by ActiveSupport Object#in?
PR #879 refactored to replace invocations of `ActiveSupport`'s' `#in?`
method. This patch follows suit to fix the following error:

```
1) Stocking is expected to validate that :bin cannot be empty/falsy
    Failure/Error: it { should validate_presence_of(:bin) }

    NoMethodError:
      undefined method `in?' for :belongs_to:Symbol
      Did you mean?  nil?
```