Add timestamptz to the dummy value case statement (#1544)
Ran into an exception when upgrading to Rails 7.0.4.2 and a column of type `timestamptz`.

```
     Failure/Error:
       is_expected.to validate_uniqueness_of(:amount).
         scoped_to(:column1, :column2, :column3, :date_time_column).
         with_message('must be unique')
     
     NoMethodError:
       undefined method `getutc' for nil:NilClass
```

After tracing, 'dummy value' was observed as being sent into this function, when then resulted in `time` being nil:
https://github.com/rails/rails/blob/v7.0.4.2/activerecord/lib/active_record/connection_adapters/postgresql/oid/timestamp_with_time_zone.rb#L122